FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libsqlcipher0 tzdata && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY kms /usr/local/bin/kms
EXPOSE 8443 9652
ENTRYPOINT ["kms"]
CMD ["serve","--http=0.0.0.0:8443"]
