apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kms-data
  namespace: lux-system
  labels:
    app: kms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
