# permissions for end users to edit kmspushsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: kmspushsecret-editor-role
rules:
  - apiGroups:
      - secrets.lux.network
    resources:
      - kmspushsecrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - secrets.lux.network
    resources:
      - kmspushsecrets/status
    verbs:
      - get
