# permissions for end users to edit kmssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kmssecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8-operator
    app.kubernetes.io/part-of: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: kmssecret-editor-role
rules:
- apiGroups:
  - secrets.lux.network
  resources:
  - kmssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.lux.network
  resources:
  - kmssecrets/status
  verbs:
  - get
