apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
  annotations:
    secrets.lux.network/auto-reload: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: static
        image: ghcr.io/hanzoai/static:latest
        envFrom:
        - secretRef:
            name: managed-secret
        ports:
        - containerPort: 80