apiVersion: secrets.lux.network/v1alpha1
kind: KMSPushSecret
metadata:
  name: kms-api-secret-sample-push
spec:
  resyncInterval: 1m
  hostAPI: https://kms.lux.network/api

  # Optional, defaults to replacement.
  updatePolicy: Replace # If set to replace, existing secrets inside KMS will be replaced by the value of the PushSecret on sync.

  # Optional, defaults to no deletion.
  deletionPolicy: Delete # If set to delete, the secret(s) inside KMS managed by the operator, will be deleted if the KMSPushSecret CRD is deleted.

  destination:
    projectId: <project-id>
    environmentSlug: <env-slug>
    secretsPath: <secret-path>

  push:
    secret:
      secretName: push-secret-source-secret # Secret CRD
      secretNamespace: default

  # Only have one authentication method defined or you are likely to run into authentication issues.
  # Remove all except one authentication method.
  authentication:
    awsIamAuth:
      identityId: <machine-identity-id>
    azureAuth:
      identityId: <machine-identity-id>
    gcpIamAuth:
      identityId: <machine-identity-id>
      serviceAccountKeyFilePath: </path-to-service-account-key-file.json>
    gcpIdTokenAuth:
      identityId: <machine-identity-id>
    kubernetesAuth:
      identityId: <machine-identity-id>
      serviceAccountRef:
        name: <secret-name>
        namespace: <secret-namespace>
    universalAuth:
      credentialsRef:
        secretName: <secret-name> # universal-auth-credentials
        secretNamespace: <secret-namespace> # default
