#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if kms is installed
if ! command -v kms >/dev/null 2>&1; then
    echo "\nError: KMS CLI is not installed. Please install the KMS CLI before comitting.\n You can refer to the documentation at https://lux.network/docs/cli/overview\n\n"
    exit 1
fi

npx lint-staged

kms scan git-changes --staged -v
