name: Run Helm Chart Tests for Gateway
on:
  pull_request:
    paths:
      - "helm-charts/kms-gateway/**"
      - ".github/workflows/run-helm-chart-tests-kms-gateway.yml"

jobs:
  test-helm:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --charts helm-charts/kms-gateway

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Create namespace
        run: kubectl create namespace kms-gateway

      - name: Create gateway secret
        run: kubectl create secret generic kms-gateway-environment --from-literal=TOKEN=my-test-token -n kms-gateway

      - name: Run chart-testing (install)
        run: |
          ct install \
            --config ct.yaml \
            --charts helm-charts/kms-gateway \
            --helm-extra-args="--timeout=300s" \
            --namespace kms-gateway
